# Generated by Django 2.2.6 on 2019-11-07 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('el_webI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_amount', models.IntegerField()),
                ('total_energy_consumed', models.IntegerField()),
            ],
        ),
    ]
