# Generated by Django 2.2.6 on 2019-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_webI', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_status',
            name='current',
            field=models.FloatField(default=0.0),
        ),
    ]
