# Generated by Django 2.2.6 on 2020-07-12 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('el_webI', '0004_auto_20200712_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='dev1',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dev2',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dev3',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dev4',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dev5',
        ),
        migrations.AddField(
            model_name='board',
            name='boardNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component_data',
            name='current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='component_data',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='component_data',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component_data',
            name='boardNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='el_webI.Board'),
        ),
        migrations.AlterField(
            model_name='component_data',
            name='deviceNo',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Component_status',
        ),
    ]
