# Generated by Django 2.2.6 on 2020-07-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_webI', '0006_auto_20200712_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_log_24hr',
            old_name='on_time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='device_log_24hr',
            old_name='oncount',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='board_log_24hr',
            name='dev1_id',
        ),
        migrations.RemoveField(
            model_name='board_log_24hr',
            name='dev2_id',
        ),
        migrations.RemoveField(
            model_name='board_log_24hr',
            name='dev3_id',
        ),
        migrations.RemoveField(
            model_name='board_log_24hr',
            name='dev4_id',
        ),
        migrations.RemoveField(
            model_name='board_log_24hr',
            name='dev5_id',
        ),
        migrations.AddField(
            model_name='board_log_24hr',
            name='boardNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='el_webI.Board'),
            preserve_default=False,
        ),
    ]
