# Generated by Django 2.2.6 on 2020-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_webI', '0007_auto_20200712_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='instant_power',
            field=models.FloatField(),
        ),
    ]
